from enum import Enum
class CandidateStatus(str, Enum):
    PENDING='PENDING'; QUEUED='QUEUED'; RUNNING='RUNNING'; COMPLETED='COMPLETED'; FAILED='FAILED'; CANCELLED='CANCELLED'; SKIPPED='SKIPPED'
class ExperimentStatus(str, Enum):
    CREATED='CREATED'; READY='READY'; RUNNING='RUNNING'; PAUSED='PAUSED'; COMPLETED='COMPLETED'; FAILED='FAILED'; CANCELLED='CANCELLED'
class ExperimentMode(str, Enum):
    SEQUENTIAL='SEQUENTIAL'; PARALLEL='PARALLEL'
class SearchMethod(str, Enum):
    GRID='GRID'; RANDOM='RANDOM'; MANUAL='MANUAL'; BAYESIAN='BAYESIAN'; GENETIC='GENETIC'
class OptimizationDirection(str, Enum):
    MAXIMIZE='MAXIMIZE'; MINIMIZE='MINIMIZE'
